export const LOGIN_AND_SIGNIN = 'LOGIN_AND_SIGNIN';
export const LOGIN_AND_SIGNIN_FAILED = 'LOGIN_AND_SIGNIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const GET_ALL_NOTES = 'GET_ALL_NOTES';
export const GET_ALL_NOTES_FAILED = 'GET_ALL_NOTES_FAILED';
export const CREATE_NOTE = 'CREATE_NOTE';
export const CREATE_NOTE_FAILED = 'CREATE_NOTE_FAILED';
export const DELETE_OR_UPDATE_NOTE = 'DELETE_OR_UPDATE_NOTE';
